.PHONY: build clean help

build:
	@go build

clean:
	@go clean

help:
	@echo "make:        compile packages and dependencies."
	@echo "make clean:  remove object files and cached files."
	@echo "make help:   display this information."
